version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal
    network_mode: bridge

  mysql:
    image: "debezium/example-mysql:1.1"
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'debezium'
      MYSQL_USER: 'mysqluser'
      MYSQL_PASSWORD: 'mysqlpw'
    network_mode: bridge
